# Generated by Django 5.2 on 2025-04-06 20:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_category_externaldatabase_parameter_columnmapping_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImportedTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('external_db', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.externaldatabase')),
            ],
        ),
        migrations.CreateModel(
            name='ImportedColumn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('data_type', models.CharField(max_length=50)),
                ('is_phi', models.BooleanField(default=False)),
                ('is_hhi', models.BooleanField(default=False)),
                ('mapped_parameter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.parameter')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.importedtable')),
            ],
        ),
    ]
