# Generated by Django 5.2 on 2025-04-07 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_importedtable_importedcolumn'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='importedcolumn',
            name='mapped_parameter',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.parameter'),
        ),
        migrations.CreateModel(
            name='Query',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QueryGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logic_operator', models.CharField(choices=[('AND', 'AND'), ('OR', 'OR'), ('NOT', 'NOT')], max_length=10)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.querygroup')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.query')),
            ],
        ),
        migrations.CreateModel(
            name='QueryCondition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operator', models.CharField(choices=[('equals', 'IS EQUAL TO'), ('not_equals', 'IS NOT EQUAL TO'), ('contains', 'CONTAINS'), ('not_contains', 'DOES NOT CONTAIN'), ('starts_with', 'STARTS WITH'), ('ends_with', 'ENDS WITH'), ('between', 'IS BETWEEN'), ('not_between', 'IS NOT BETWEEN'), ('exists', 'EXISTS'), ('not_exists', 'DOES NOT EXIST')], max_length=30)),
                ('value', models.TextField(blank=True, null=True)),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.parameter')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.querygroup')),
            ],
        ),
    ]
