# Generated by Django 5.2 on 2025-04-17 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_uniqueidmap_columnmapping_source_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='querygroup',
            name='logic_operator',
        ),
        migrations.AddField(
            model_name='querycondition',
            name='logic',
            field=models.CharField(default='AND', max_length=20),
        ),
        migrations.AddField(
            model_name='querycondition',
            name='value0',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='querycondition',
            name='value1',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='querygroup',
            name='logic',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR'), ('AND NOT', 'AND NOT')], default='OR', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='query',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='querycondition',
            name='operator',
            field=models.CharField(max_length=50),
        ),
    ]
