# Generated by Django 5.2 on 2025-04-17 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_remove_querygroup_logic_operator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querycondition',
            name='logic',
            field=models.CharField(default='AND', max_length=20, null=True),
        ),
    ]
