# Generated by Django 5.2 on 2025-04-17 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_alter_querycondition_logic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querygroup',
            name='logic',
            field=models.CharField(choices=[('AND', 'AND'), ('OR', 'OR'), ('AND NOT', 'AND NOT')], max_length=20, null=True),
        ),
    ]
