# Generated by Django 5.2 on 2025-04-18 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_querygroup_logic'),
    ]

    operations = [
        migrations.AddField(
            model_name='querycondition',
            name='position',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='querygroup',
            name='position',
            field=models.IntegerField(default=0),
        ),
    ]
