# Generated by Django 5.2 on 2025-05-15 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_importedtable_table_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='subcategory',
        ),
        migrations.AddField(
            model_name='parameter',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='main.subcategory'),
        ),
    ]
