# Generated by Django 5.2 on 2025-05-15 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_parameter_subcategory_parameter_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='subcategories',
            field=models.ManyToManyField(blank=True, related_name='parameters', to='main.subcategory'),
        ),
    ]
