# Generated by Django 5.2 on 2025-05-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_parameter_subcategories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='subcategories',
            field=models.ManyToManyField(blank=True, to='main.subcategory'),
        ),
    ]
