# Generated by Django 5.2 on 2025-05-16 00:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_parameter_subcategories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='parameter',
            name='subcategories',
        ),
        migrations.AddField(
            model_name='parameter',
            name='subcategory',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.CASCADE, to='main.subcategory'),
            preserve_default=False,
        ),
    ]
