# Generated by Django 5.2 on 2025-05-16 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_parameter_subcategories_parameter_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='importedtable',
            name='patient_id_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='importedtable',
            name='study_id_column',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
