# Generated by Django 5.2 on 2025-06-02 07:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_unit_unitconversion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='target_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.unit'),
        ),
    ]
