# Generated by Django 5.2 on 2025-06-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_alter_parameter_target_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parameter',
            name='target_unit',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.DeleteModel(
            name='UnitConversion',
        ),
        migrations.DeleteModel(
            name='Unit',
        ),
    ]
